name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x', '7.0.x']

    steps:
    - uses: actions/checkout@v3
    - name: Set Up .NET ${{matrix.dotnet-version}}
      uses: actions/setup-dotnet@v3
      id: setup
      with:
        dotnet-version: ${{matrix.dotnet-version}}
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Create global.json
      run: echo '{"sdk":{"version":"${{steps.setup.outputs.dotnet-version}}"}}' > ./global.json
    - name: Run Build Script
      run: pwsh ./build-package.ps1 -WithBinLog -Configuration Release
    - name: Store Log for Failed Build
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: MSBuild Log File (.NET SDK ${{steps.setup.outputs.dotnet-version}})
        path: msbuild.binlog
    - name: Store NuGet Package
      uses: actions/upload-artifact@v3
      with:
        name: NuGet Package (.NET SDK ${{steps.setup.outputs.dotnet-version}})
        path: ./**/bin/Release/*.nupkg
    - name: Show current ref
      run: 'echo github.ref: ${{github.ref}}'
    - name: Publish NuGet Package
      if: startsWith(github.ref, 'refs/tags/v')
      run: dotnet nuget push */bin/Release/*.nupkg
