name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      dotnet-version: 7.0.x
    strategy:
      matrix:
        configuration: ['Debug', 'Release']

    steps:
    - name: Check out the project
      uses: actions/checkout@v3
    - name: Set up .NET ${{env.dotnet-version}}
      uses: actions/setup-dotnet@v3
      id: setup
      with:
        dotnet-version: ${{env.dotnet-version}}
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Create global.json to force use of .NET SDK ${{steps.setup.outputs.dotnet-version}}
      run: echo '{"sdk":{"version":"${{steps.setup.outputs.dotnet-version}}"}}' > ./global.json
    - name: Run build script (${{matrix.configuration}})
      run: pwsh ./build-package.ps1 -WithBinLog -Configuration ${{matrix.configuration}}
    - name: "Artifact: MSBuild Logs"
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: MSBuild Logs (${{matrix.configuration}})
        path: msbuild.*.binlog
    - name: "Artifact: NuGet Packages"
      uses: actions/upload-artifact@v3
      with:
        name: NuGet Packages (${{matrix.configuration}})
        path: "**/bin/${{matrix.configuration}}/*.nupkg"
    - name: Publish (NuGet - GitHub Packages)
      if: matrix.configuration == 'Release' # && startsWith(github.ref, 'refs/tags/v')
      run: "dotnet nuget push */bin/${{matrix.configuration}}/*.nupkg"
